theme: noesya-hugo-theme
_merge: deep
params:
  plausible: maison.noesya.coop
  ecosystem: maison
  summary:
    position: hero
  search:
    active: false
  home:
    head:
      title: site
  posts:
    index:
      options:
        image: false